base_path: .
base_url: "https://beytok.crowdin.com/"
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

files:
  - source: main/src/main/resources/lang/lang.json
    translation: >-
      main/src/main/resources/lang/%two_letters_code%/%original_file_name%
